"""empty message

Revision ID: b2606c294e07
Revises: 703aeee2673a
Create Date: 2024-05-22 19:51:26.336656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2606c294e07'
down_revision = '703aeee2673a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('teste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
